name: Deploy to Namecheap Server

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Replace with the latest version that supports Node.js 20

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0 # Replace with the latest version that supports Node.js 20
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to Namecheap Server
        run: |
          scp -r -P 21098 * junecqhi@198.54.114.247:/home/junecqhi/public_html/
